on:
  push:
    branches: ["master"]
  pull_request:

name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  RUSTFLAGS: -Dwarnings
  RUST_BACKTRACE: 1
  rust_stable: stable
  rust_min: "1.92"

permissions:
  contents: read

jobs:
  # Basic checks that must pass before we kick off more expensive tests.
  basics:
    name: basic checks
    runs-on: ubuntu-latest
    needs:
      - clippy
      - fmt
      - docs
      - minrust
    steps:
      - run: exit 0

  test:
    needs: basics
    name: test - ${{ matrix.os }} - ${{ matrix.features }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
        features:
          - "--no-default-features"
          - "--features crossterm"
          - "--all-features"
    steps:
      - uses: actions/checkout@v6
      - name: Install Rust ${{ env.rust_stable }}
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.rust_stable }}

      - uses: Swatinem/rust-cache@v2

      - name: test ${{ matrix.features }}
        run: cargo test ${{ matrix.features }} --lib --doc

  fmt:
    name: fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Rust ${{ env.rust_stable }}
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.rust_stable }}
          components: rustfmt

      - uses: Swatinem/rust-cache@v2

      # Check fmt
      - name: "rustfmt --check"
        run: |
          if ! rustfmt --check --edition 2021 $(git ls-files '*.rs'); then
            printf "Please run \`rustfmt --edition 2021 \$(git ls-files '*.rs')\` to fix rustfmt errors.\n" >&2
            exit 1
          fi

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Rust ${{ env.rust_stable }}
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.rust_stable }}
          components: clippy

      - uses: Swatinem/rust-cache@v2

      # Run clippy
      - name: "clippy --all-features"
        run: cargo clippy --all-targets --all-features -- -D warnings


  docs:
    name: docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Rust ${{ env.rust_nightly }}
        uses: dtolnay/rust-toolchain@nightly

      - uses: Swatinem/rust-cache@v2

      - name: "cargo doc --all-features"
        run: cargo doc --no-deps --all-features --document-private-items
        env:
          RUSTDOCFLAGS: -D warnings

  minrust:
    name: minrust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Rust ${{ env.rust_min }}
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.rust_min }}

      - uses: Swatinem/rust-cache@v2

      - name: "cargo check --all-features"
        run: cargo check --all-features

  minimal-versions:
    name: minimal-versions
    needs: basics
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Rust nightly
        uses: dtolnay/rust-toolchain@nightly

      - uses: Swatinem/rust-cache@v2

      - name: "check -Z minimal-versions"
        run: |
          cargo update -Z minimal-versions
          cargo check --all-features
